name: Draft PDF

on:
  push:
    paths:
      - 'paper/paper.md'
      - 'paper/paper.bib'
      - 'paper/Fig*.png'
      - '.github/workflows/draft-pdf.yml'

permissions:
  contents: write       # so the workflow can commit the PDF back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper
          path: paper.pdf

      - name: Commit PDF back to repo
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) add draft paper.pdf'
          add: 'paper.pdf'